### PR TITLE
style: resolve react/display-name

### PR DESCRIPTION
**Pull request by douglasduteil**
tenor 30

### CODE REVIEW

**Comment by revolunet** [comment]
on a plus le droit au double/triple arrows ?

**Comment by douglasduteil** [comment]
Names allow better debugging

\following https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md

**Comment by revolunet** [comment]
i think it only work if you give the function a name ?

**Comment by douglasduteil** [comment]
I think it works if the statement as a name (given by a variable, function) or if you use the static `displayName`

**Comment by revolunet** [comment]
for example, the selected one is the same as fat-arrow ?

capture d ecran 2018-10-17 a 18 06 32

**Pull request merged**
