### PR TITLE
style: replace right single quotation mark by single quote

### PR DESCRIPTION
**Pull request by douglasduteil**
`’` is not `'`.

This was a tricky one...

I don't know from where it comes from...

### CODE REVIEW

**Comment by revolunet** [comment]
Copier/coller + Windows ?

**Comment by douglasduteil** [comment]
Dunno ¯\_(ツ)_/¯

**Comment by douglasduteil** [comment]
\ping @revolunet 
this PR doesn't resolve the lint problem.
\following [eslint-plugin-react#docs/rules/no-unescaped-entities.md](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md)

```jsx
<br />
C 'est à la fois un lieu, une démarche et un ensemble de personnes !
<br />
<br />
L 'incubateur des ministères sociaux reprend la démarche et les grands principes de{" "}
<a href="http://beta.gouv.fr" target="_blank" rel="noopener noreferrer">
  beta.gouv
</a>
```

Is not valid because `'` (quotes) are forbidden in text.

We will need to choose between, 

- replacing them for HTML code (`&apos;`, `&lsquo;`, `&#39;` or `&rsquo;`)

```diff
 <br />
-C 'est à la fois un lieu, une démarche et un ensemble de personnes !
+C&apos;est à la fois un lieu, une démarche et un ensemble de personnes !
 <br />
 <br />
-L 'incubateur des ministères sociaux reprend la démarche et les grands principes de{" "}
+L&apos;incubateur des ministères sociaux reprend la démarche et les grands principes de{" "}
 <a href="http://beta.gouv.fr" target="_blank" rel="noopener noreferrer">
   beta.gouv
 </a>
```

- wrapping the content in a subexpression

```diff
 <br />
-C 'est à la fois un lieu, une démarche et un ensemble de personnes !
+{"C 'est à la fois un lieu, une démarche et un ensemble de personnes !"}
 <br />
 <br />
-L 'incubateur des ministères sociaux reprend la démarche et les grands principes de{" "}
+{"L 'incubateur des ministères sociaux reprend la démarche et les grands principes de "}
 <a href="http://beta.gouv.fr" target="_blank" rel="noopener noreferrer">
   beta.gouv
 </a>
```

- removing `'` (quotes) from forbidden characters in texts

**Comment by douglasduteil** [comment]
:up: @revolunet

**Pull request merged**
