### PR TITLE
First version of WIF timeline

### PR DESCRIPTION
**Pull request by adipasquale**
As discussed during a petit seminaire, we are adding timelines to the startups pages. The first startup is Work In France thanks to Siegrid Henry's work (cf [this spreadsheet](https://docs.google.com/spreadsheets/d/1UHmBeacYPPtuHXpB6AquV3CKMs_Vl6GneLmFyc-M4cY/edit#gid=483764309))

This is not ready to deploy, I think we should limit ourselves to 5-10 events max.

I'm using the [react-vertical-timeline](https://github.com/stephane-monnot/react-vertical-timeline/) package as recommended by @revolunet . I also added the [react-icons](https://github.com/react-icons/react-icons) package to have a few nice icons. this gives us access to all of the [Font Awesome](https://fontawesome.com/v4.7.0/icons/) icons and the Material Design ones.

live demo version https://socialgouvgithubio-azsxl9x7w.now.sh/startups/work-in-france

Screenshots:

Screen Shot 2019-04-19 at 20 45 52

Capture d’écran - 2019-04-19 à 20 45 39

😎 🇫🇷 pushed from the Channel Tunnel 🇬🇧 🚄

### CODE REVIEW

**Comment by adipasquale** [comment]
second version: I refactored the code to be more flexible, you now use components `Timeline` and `TimelineEvent` directly in the startup page's MDX.

This makes embedding photos possible :) or you could imagine adding subtitles too.
Screen Shot 2019-04-23 at 19 42 31

@ siegrid: I took this photo just for the test, feel free to remove it.

The downside is that the Timeline is now embedded into the article's layout so it doesn't span all the page anymore. Not sure if it's better or worse.

**Comment by douglasduteil** [comment]
Les contrats espacement et couleurs son pas ouf 😏
Je vais faire une p'tite lifting. Hold my beer !

**Comment by adipasquale** [comment]
j'ai littéralement mis des couleurs au hasard 😬

**Comment by lionelB** [comment]
en tout cas c'est cool !

**Comment by revolunet** [comment]
rebased at #367

**Comment by revolunet** [comment]
``

**Pull request closed without merging**
